[package]
name = "natrium"
version = "0.1.0"
authors = ["Rynco Maekawa <lynzrand@outlook.com>"]
edition = "2018"

[dependencies]
"combine" = "^4.0.1"
"r0vm" = { path = "crates/r0vm" }
# "r0syntax" = { path = "crates/syntax" }
