[package]
name = "natrium"
version = "0.1.0"
authors = ["Rynco Maekawa <lynzrand@outlook.com>"]
edition = "2018"

[dependencies]
"r0vm" = { path = "crates/r0vm", default-features = false }
"r0syntax" = { path = "crates/syntax" }

# inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm9-0", optional = true }
[features]
default = ["vm"]
# llvm9 = ["inkwell"]
vm = ["r0vm/vm"]

[workspace]
members = ["crates/*"]
